"""Integrity checks for the real C-MAPSS raw data (pulled via `dvc pull`).

Checks file presence, row/column counts and per-dataset unit counts against
configs/data_expectations.json, generated by reading data/raw directly
(see that file's _comment). This catches a corrupted pull, a DVC remote
pointing at the wrong data, or the raw files changing underneath us.
"""

from __future__ import annotations

import json
from pathlib import Path

import pandas as pd
import pytest

pytestmark = pytest.mark.requires_data

RAW = Path("data/raw")
EXPECTATIONS = json.loads(
    (Path(__file__).parents[1] / "configs" / "data_expectations.json").read_text()
)["datasets"]
DATASETS = tuple(EXPECTATIONS)


def _read_raw(path: Path) -> pd.DataFrame:
    return pd.read_csv(path, sep=r"\s+", header=None)


@pytest.mark.parametrize("dataset", DATASETS)
class TestFilePresence:
    def test_train_file_exists(self, dataset: str) -> None:
        assert (RAW / f"train_{dataset}.txt").exists()

    def test_test_file_exists(self, dataset: str) -> None:
        assert (RAW / f"test_{dataset}.txt").exists()

    def test_rul_file_exists(self, dataset: str) -> None:
        assert (RAW / f"RUL_{dataset}.txt").exists()


@pytest.mark.parametrize("dataset", DATASETS)
class TestRowColCounts:
    def test_train_shape(self, dataset: str) -> None:
        exp = EXPECTATIONS[dataset]
        df = _read_raw(RAW / f"train_{dataset}.txt")
        assert df.shape == (exp["train_rows"], exp["train_cols"])

    def test_test_shape(self, dataset: str) -> None:
        exp = EXPECTATIONS[dataset]
        df = _read_raw(RAW / f"test_{dataset}.txt")
        assert df.shape == (exp["test_rows"], exp["test_cols"])

    def test_rul_shape(self, dataset: str) -> None:
        exp = EXPECTATIONS[dataset]
        df = _read_raw(RAW / f"RUL_{dataset}.txt")
        assert df.shape == (exp["rul_rows"], exp["rul_cols"])


@pytest.mark.parametrize("dataset", DATASETS)
class TestUnitCounts:
    def test_train_unit_count(self, dataset: str) -> None:
        exp = EXPECTATIONS[dataset]
        df = _read_raw(RAW / f"train_{dataset}.txt")
        assert df[0].nunique() == exp["train_units"]

    def test_test_unit_count(self, dataset: str) -> None:
        exp = EXPECTATIONS[dataset]
        df = _read_raw(RAW / f"test_{dataset}.txt")
        assert df[0].nunique() == exp["test_units"]

    def test_rul_row_count_matches_test_units(self, dataset: str) -> None:
        """One RUL value per test engine — a structural invariant, not just a fixture match."""
        exp = EXPECTATIONS[dataset]
        assert exp["rul_rows"] == exp["test_units"]
